### PR TITLE
Don't create the same permissions as default launchers

### LINKED ISSUE #6: Conflicting permissions
Hello,

This app can't be installed on Fairphone OS:
```
Package community.fairphone.fplauncher3 attempting to redeclare permission com.android.launcher3.permission.RECEIVE_FIRST_LOAD_BROADCAST already owned by com.fairphone.fplauncher3
```

Or on LineageOS:
```
Package community.fairphone.fplauncher3 attempting to redeclare permission com.android.launcher3.permission.RECEIVE_FIRST_LOAD_BROADCAST already owned by com.cyanogenmod.trebuchet
```
(And probably on some other Android ROMs too.)

This is because the `com.android.launcher3.permission.*` permissions are already used by most default launchers (because most of them are forks of the AOSP launcher).

Would it be possible to rename the permissions to something else?

### PR DESCRIPTION
**Pull request by Rudloff**
Fixes #6

### CODE REVIEW

**Comment by Rudloff** [comment]
@Roboe Would it be possible to publish a new tagged release once this patch is merged?
It will fix the install on a lot of devices so I think it makes sense to publish an update on F-Droid.

**Comment by Roboe** [comment]
> Would it be possible to publish a new tagged release once this patch is merged?

Yes, of course

**Comment by Rudloff** [comment]
Oh I didn't know about this dot notation. I updated my PR.

> Just be sure it installs fine at least in Fairphone OS/Open and LineageOS.
I don't have LOS anymore but I confirm it works correctly on Fairphone Open.

**Comment by Roboe** [comment]
Could you enable "Allow edits from maintainers" in the side options of this PR, please?

**Comment by Rudloff** [comment]
It is already enabled.

**Comment by Roboe** [comment]
@Rudloff @Bubu I confirm it installs and launch correctly on LineageOS

**Comment by Rudloff** [comment]
@Roboe Is everything OK for you or do I need to make some other changes?

**Comment by Roboe** [comment]
I forgot to approve the changes, sorry. You can tag a new release if you want.
If you consider #9 an easy task, you can maybe include that too in the release. Whatever you consider will be great, :)

Thank you!

**Pull request merged**
